// Generated by tools/screen_tool.tcl from screens.txt; edit that file, not this one.
// Pages, dynamic value sources and memory sizes of the text screens (char_screen).

package ui_pkg;

  localparam int PAGE_CELLS  = 4800;
  localparam int NUM_PAGES   = 6;
  localparam int PAGE_WORDS  = 28800;
  localparam int MAX_FIELDS  = 64;
  localparam int NUM_FIELDS  = 17;
  localparam int MAX_WORDS   = 64;
  localparam int NUM_SOURCES = 13;

  localparam logic [2:0] PAGE_NONE = 3'd0;
  localparam logic [2:0] PAGE_MODE = 3'd1;   // scale 2
  localparam logic [2:0] PAGE_NOAI = 3'd2;   // scale 2
  localparam logic [2:0] PAGE_WATCH = 3'd3;   // scale 2
  localparam logic [2:0] PAGE_WATCHDBG = 3'd4;   // scale 1
  localparam logic [2:0] PAGE_SETUP = 3'd5;   // scale 2
  localparam logic [2:0] PAGE_TRAINSTUB = 3'd6;   // scale 2
  localparam logic [7:0] PAGE_SCALE2 = 8'b01101110;   // bit p = page p uses 16x16 cells

  localparam int SRC_MODE_CURSOR = 0;
  localparam int SRC_NOAI_CURSOR = 1;
  localparam int SRC_AI_ACTION = 2;
  localparam int SRC_AI_F0 = 3;
  localparam int SRC_AI_F1 = 4;
  localparam int SRC_AI_F2 = 5;
  localparam int SRC_AI_F3 = 6;
  localparam int SRC_AI_H0 = 7;
  localparam int SRC_AI_Y = 8;
  localparam int SRC_WORLD_SPEED = 9;
  localparam int SRC_TRAIN_DIFF = 10;
  localparam int SRC_TRAIN_CORALS = 11;
  localparam int SRC_TRAIN_SPEED = 12;

  localparam logic [2:0] FMT_DEC    = 3'd0;
  localparam logic [2:0] FMT_DECB   = 3'd1;
  localparam logic [2:0] FMT_SDEC   = 3'd2;
  localparam logic [2:0] FMT_HEX    = 3'd3;
  localparam logic [2:0] FMT_WORD   = 3'd4;
  localparam logic [2:0] FMT_CURSOR = 3'd5;

endpackage
