# Converts a text sound-effect description into songs.mif for the supplied
# melody_player_1.sv (RTL/AUDIO/melody_player_1.sv, unmodified).
#
# Usage (from the repository root):
#   quartus_sh -t tools/audio_tool.tcl assets/audio/effects.txt fpga/RTL/AUDIO/songs.mif
#
# Word layout (matches melody_player_1.sv exactly):
#   bits [15:12] tone   (0..11, one of the 12 semitones below; NOT 12..15)
#   bits [11:10] octave field (0..3 -> real octave 3..6)
#   bits [9:5]   duration, units of 30 ms (mSecPerTick=30 in melody_player_1)
#   bits [4:0]   gap,      units of 30 ms
# Address = {melodySelect[3:0], noteIndex[7:0]} -> depth 4096, 16 melody
# slots of 256 notes each. duration = 0 marks the end of a melody, and the
# generator appends it automatically; every other word defaults to 0.

proc fail {msg} {
    puts stderr "audio_tool: $msg"
    exit 1
}

array set NOTE_INDEX {
    do 0  doD 1  re 2  reD 3  mi 4  fa 5  faD 6  sol 7  solD 8  la 9  laD 10  si 11
}

proc round_to_tick {ms tickMs src} {
    if {$ms % $tickMs != 0} {
        puts stderr "audio_tool: $src: ${ms} ms is not a multiple of ${tickMs} ms; rounding"
    }
    set units [expr {int(($ms + $tickMs / 2) / $tickMs)}]
    if {$units > 31} { fail "$src: ${ms} ms exceeds the 31-tick (930 ms) maximum" }
    return $units
}

proc parse_effects {src} {
    global NOTE_INDEX
    set fh [open $src r]
    set lines [split [read $fh] "\n"]
    close $fh

    set melodies [dict create]
    set curIndex ""
    set curNotes {}

    for {set i 0} {$i < [llength $lines]} {incr i} {
        set line [string trim [lindex $lines $i]]
        if {$line eq "" || [string index $line 0] eq "#"} { continue }
        set words [regexp -all -inline {\S+} $line]
        set loc "$src line [expr {$i + 1}]"

        if {[lindex $words 0] eq "melody"} {
            if {$curIndex ne ""} { dict set melodies $curIndex $curNotes }
            set curIndex [lindex $words 1]
            if {![string is integer $curIndex] || $curIndex < 0 || $curIndex > 15} {
                fail "$loc: melody index must be 0..15"
            }
            if {[dict exists $melodies $curIndex]} { fail "$loc: melody $curIndex defined twice" }
            set curNotes {}
            continue
        }

        if {$curIndex eq ""} { fail "$loc: note line before any 'melody' header" }
        if {[llength $words] != 4} { fail "$loc: expected '<note> <octave> <duration_ms> <gap_ms>'" }
        lassign $words noteName octave durMs gapMs
        if {![info exists NOTE_INDEX($noteName)]} { fail "$loc: unknown note '$noteName'" }
        if {![string is integer $octave] || $octave < 3 || $octave > 6} { fail "$loc: octave must be 3..6" }
        set duration [round_to_tick $durMs 30 $loc]
        set gap      [round_to_tick $gapMs 30 $loc]
        if {$duration == 0} { fail "$loc: a note's duration cannot round to 0 (that marks end-of-song)" }
        lappend curNotes [list $NOTE_INDEX($noteName) [expr {$octave - 3}] $duration $gap]
    }
    if {$curIndex ne ""} { dict set melodies $curIndex $curNotes }
    return $melodies
}

proc write_mif {dst melodies} {
    set depth 4096
    set words [lrepeat $depth 0]
    dict for {index notes} $melodies {
        set noteIndex 0
        foreach note $notes {
            if {$noteIndex >= 255} { fail "melody $index: too many notes (max 255 plus the end marker)" }
            lassign $note tone octaveField duration gap
            set word [expr {($tone << 12) | ($octaveField << 10) | ($duration << 5) | $gap}]
            lset words [expr {($index << 8) | $noteIndex}] $word
            incr noteIndex
        }
        ;# word 0 (duration field 0) at noteIndex is already the end-of-song marker
    }

    file mkdir [file dirname $dst]
    set fh [open $dst w]
    fconfigure $fh -translation lf
    puts $fh "-- Generated by tools/audio_tool.tcl from [file tail [lindex $::argv 0]]; edit the .txt, not this file."
    puts $fh "-- 16 melody slots x 256 notes, address = {melodySelect, noteIndex}, matches melody_player_1.sv."
    puts $fh "DEPTH = $depth;"
    puts $fh "WIDTH = 16;"
    puts $fh "ADDRESS_RADIX = HEX;"
    puts $fh "DATA_RADIX = HEX;"
    puts $fh "CONTENT BEGIN"
    for {set a 0} {$a < $depth} {incr a} {
        puts $fh [format "%03X : %04X;" $a [lindex $words $a]]
    }
    puts $fh "END;"
    close $fh
}

if {[llength $quartus(args)] != 2} {
    fail "usage: quartus_sh -t tools/audio_tool.tcl <effects.txt> <songs.mif>"
}
lassign $quartus(args) src dst
set melodies [parse_effects $src]
if {[dict size $melodies] == 0} { fail "$src: no melodies defined" }
write_mif $dst $melodies
puts "audio_tool: [dict size $melodies] melodies from $src -> $dst"
