# Converts the text bitmap font into a 1-bit Quartus .mif.
#
# Usage (from the repository root):
#   quartus_sh -t tools/font_tool.tcl <font.txt> <out.mif>
#
# Font file: "glyph <char>" (or "glyph space") followed by 7 rows of 7
# characters, '#' = ink, '.' = paper. Each glyph fills an 8x8 cell (the last
# column and row stay empty). The ROM holds ASCII 0x20..0x5F; the address is
# {code - 0x20 (6 bits), y (3 bits), x (3 bits)}.

proc fail {msg} {
    puts stderr "font_tool: $msg"
    exit 1
}

lassign $quartus(args) src dst
if {$src eq "" || $dst eq ""} { fail "usage: quartus_sh -t tools/font_tool.tcl <font.txt> <out.mif>" }

set bits [lrepeat 4096 0]
set fh [open $src r]
set lines [split [read $fh] "\n"]
close $fh

set count 0
for {set i 0} {$i < [llength $lines]} {incr i} {
    set line [string trim [lindex $lines $i]]
    if {$line eq "" || [string index $line 0] eq "#"} { continue }
    if {![regexp {^glyph\s+(\S+)$} $line -> name]} { fail "line [expr {$i + 1}]: expected 'glyph <char>'" }
    set ch [expr {$name eq "space" ? " " : $name}]
    if {[string length $ch] != 1} { fail "line [expr {$i + 1}]: bad glyph name '$name'" }
    scan $ch %c code
    if {$code < 0x20 || $code > 0x5F} { fail "glyph '$ch' is outside ASCII 0x20..0x5F" }
    set index [expr {$code - 0x20}]
    for {set y 0} {$y < 7} {incr y} {
        incr i
        set row [string trimright [lindex $lines $i] "\r"]
        if {[string length $row] != 7 || ![regexp {^[.#]+$} $row]} {
            fail "line [expr {$i + 1}]: glyph '$ch' row must be 7 of '.' or '#'"
        }
        for {set x 0} {$x < 7} {incr x} {
            if {[string index $row $x] eq "#"} {
                lset bits [expr {($index << 6) | ($y << 3) | $x}] 1
            }
        }
    }
    incr count
}

file mkdir [file dirname $dst]
set fh [open $dst w]
fconfigure $fh -translation lf
puts $fh "-- Generated by tools/font_tool.tcl from [file tail $src]; edit the .txt, not this file."
puts $fh "-- 64 glyphs (ASCII 0x20..0x5F), 8x8 cells, address = {code - 0x20, y, x}"
puts $fh "DEPTH = 4096;"
puts $fh "WIDTH = 1;"
puts $fh "ADDRESS_RADIX = HEX;"
puts $fh "DATA_RADIX = BIN;"
puts $fh "CONTENT BEGIN"
for {set a 0} {$a < 4096} {incr a} {
    puts $fh [format "%03X : %d;" $a [lindex $bits $a]]
}
puts $fh "END;"
close $fh
puts "font_tool: $count glyphs -> $dst"
