# Converts a network description (37 signed 8-bit genes) into the files the
# design and the testbenches load.
#
# Usage (from the repository root):
#   quartus_sh -t tools/nn_tool.tcl <net.txt> <out.mif> <out.hex>
#
# Input: one "<gene> <value> [comment]" per line, genes 0..36 in any order,
# values -128..127; '#' starts a comment line. Genes not listed are zero.
# The .mif has 64 words (the memory size); the .hex has the 37 genes for
# $readmemh.

proc fail {msg} {
    puts stderr "nn_tool: $msg"
    exit 1
}

set GENES 37
lassign $quartus(args) src mif hex
if {$src eq "" || $mif eq "" || $hex eq ""} {
    fail "usage: quartus_sh -t tools/nn_tool.tcl <net.txt> <out.mif> <out.hex>"
}

set values [lrepeat 64 0]
set seen {}
set fh [open $src r]
set n 0
foreach line [split [read $fh] "\n"] {
    incr n
    set line [string trim $line]
    if {$line eq "" || [string index $line 0] eq "#"} { continue }
    if {![regexp {^(\d+)\s+(-?\d+)} $line -> gene value]} { fail "line $n: expected '<gene> <value>'" }
    scan $gene %d gene
    scan $value %d value
    if {$gene >= $GENES} { fail "line $n: gene $gene is outside 0..[expr {$GENES - 1}]" }
    if {$value < -128 || $value > 127} { fail "line $n: value $value is outside -128..127" }
    if {[lsearch $seen $gene] >= 0} { fail "line $n: gene $gene listed twice" }
    lappend seen $gene
    lset values $gene [expr {$value & 0xFF}]
}
close $fh

foreach {path} [list $mif $hex] { file mkdir [file dirname $path] }

set fh [open $mif w]
fconfigure $fh -translation lf
puts $fh "-- Generated by tools/nn_tool.tcl from [file tail $src]; edit the .txt, not this file."
puts $fh "DEPTH = 64;"
puts $fh "WIDTH = 8;"
puts $fh "ADDRESS_RADIX = DEC;"
puts $fh "DATA_RADIX = HEX;"
puts $fh "CONTENT BEGIN"
for {set a 0} {$a < 64} {incr a} {
    puts $fh [format "%d : %02X;" $a [lindex $values $a]]
}
puts $fh "END;"
close $fh

set fh [open $hex w]
fconfigure $fh -translation lf
puts $fh "// Generated by tools/nn_tool.tcl from [file tail $src]"
for {set a 0} {$a < $GENES} {incr a} {
    puts $fh [format "%02X" [lindex $values $a]]
}
close $fh

puts "nn_tool: [llength $seen] genes from [file tail $src] -> [file tail $mif], [file tail $hex]"
