# Builds the initial population memory of the on-chip trainer (M10).
#
# Usage (from the repository root):
#   quartus_sh -t tools/pop_tool.tcl <pop.txt> <out.mif> <out.hex>
#
# pop.txt:
#   seed <n>                         seed of the generator for the random candidates
#   slot <c> <gene>=<value> ...      hand-set candidate c (genes not listed are 0)
# Every other slot gets 37 random genes, uniform in -64..63.
# '#' starts a comment line.
#
# The memory has 64 candidates x 64 gene slots (address {candidate, gene});
# gene slots 37..63 are 0. The .hex lists the same 4,096 words for $readmemh.

proc fail {msg} {
    puts stderr "pop_tool: $msg"
    exit 1
}

set CANDS 64
set GENES 37
lassign $quartus(args) src mif hex
if {$src eq "" || $mif eq "" || $hex eq ""} {
    fail "usage: quartus_sh -t tools/pop_tool.tcl <pop.txt> <out.mif> <out.hex>"
}

set seed 1
set hand [dict create]
set fh [open $src r]
set n 0
foreach line [split [read $fh] "\n"] {
    incr n
    set line [string trim $line]
    if {$line eq "" || [string index $line 0] eq "#"} { continue }
    set words [regexp -all -inline {\S+} $line]
    switch -- [lindex $words 0] {
        seed {
            set seed [lindex $words 1]
            if {![string is integer -strict $seed] || $seed <= 0} { fail "line $n: seed must be a positive integer" }
        }
        slot {
            set c [lindex $words 1]
            if {![string is integer -strict $c] || $c < 0 || $c >= $CANDS} { fail "line $n: slot outside 0..[expr {$CANDS - 1}]" }
            if {[dict exists $hand $c]} { fail "line $n: slot $c listed twice" }
            set genes [lrepeat $GENES 0]
            foreach item [lrange $words 2 end] {
                if {![regexp {^(\d+)=(-?\d+)$} $item -> gene value]} { fail "line $n: expected gene=value, got '$item'" }
                scan $gene %d gene
                scan $value %d value
                if {$gene >= $GENES} { fail "line $n: gene $gene outside 0..[expr {$GENES - 1}]" }
                if {$value < -128 || $value > 127} { fail "line $n: value $value outside -128..127" }
                lset genes $gene $value
            }
            dict set hand $c $genes
        }
        default { fail "line $n: unexpected '[lindex $words 0]'" }
    }
}
close $fh

# 32-bit xorshift (13, 17, 5)
set rng [expr {$seed & 0xFFFFFFFF}]
proc next_rand {} {
    global rng
    set x $rng
    set x [expr {($x ^ ($x << 13)) & 0xFFFFFFFF}]
    set x [expr {$x ^ ($x >> 17)}]
    set x [expr {($x ^ ($x << 5)) & 0xFFFFFFFF}]
    set rng $x
    return $x
}

set words {}
for {set c 0} {$c < $CANDS} {incr c} {
    if {[dict exists $hand $c]} {
        set genes [dict get $hand $c]
    } else {
        set genes {}
        for {set g 0} {$g < $GENES} {incr g} {
            lappend genes [expr {([next_rand] & 127) - 64}]
        }
    }
    for {set g 0} {$g < 64} {incr g} {
        set v 0
        if {$g < $GENES} { set v [lindex $genes $g] }
        lappend words [expr {$v & 0xFF}]
    }
}

foreach path [list $mif $hex] { file mkdir [file dirname $path] }

set fh [open $mif w]
fconfigure $fh -translation lf
puts $fh "-- Generated by tools/pop_tool.tcl from [file tail $src]; edit the .txt, not this file."
puts $fh "-- Address = candidate * 64 + gene."
puts $fh "DEPTH = [llength $words];"
puts $fh "WIDTH = 8;"
puts $fh "ADDRESS_RADIX = DEC;"
puts $fh "DATA_RADIX = HEX;"
puts $fh "CONTENT BEGIN"
set a 0
foreach w $words {
    puts $fh [format "%d : %02X;" $a $w]
    incr a
}
puts $fh "END;"
close $fh

set fh [open $hex w]
fconfigure $fh -translation lf
puts $fh "// Generated by tools/pop_tool.tcl from [file tail $src]; address = candidate * 64 + gene"
foreach w $words { puts $fh [format "%02X" $w] }
close $fh

puts "pop_tool: [dict size $hand] hand-set and [expr {$CANDS - [dict size $hand]}] random candidates -> [file tail $mif], [file tail $hex]"
