# Converts a text pixel-art sprite into a Quartus .mif and an optional HTML preview.
#
# Usage (from the repository root):
#   quartus_sh -t tools/sprite_tool.tcl <sprite.txt> <out.mif> [preview.html]
#
# Sprite file format:
#   # comment
#   size <W> <H>                       width and height, both powers of two
#   palette <char> <RRRGGGBB hex> <description...>
#   base                               followed by H rows (optional)
#   frame                              followed by H rows; repeat per frame
# With a base, frame rows are overlays: '.' keeps the base pixel, '_' forces
# transparency. Without a base, each frame is a complete image.
# The ROM address is {frame, y, x}, so W, H and the frame count set the depth.

proc fail {msg} {
    puts stderr "sprite_tool: $msg"
    exit 1
}

proc is_pow2 {n} {
    return [expr {$n > 0 && ($n & ($n - 1)) == 0}]
}

proc read_grid {lines idxVar w h src} {
    upvar $idxVar idx
    set grid {}
    for {set y 0} {$y < $h} {incr y} {
        incr idx
        if {$idx >= [llength $lines]} { fail "$src: grid ended early" }
        set row [string trimright [lindex $lines $idx] "\r"]
        if {[string length $row] != $w} {
            fail "$src line [expr {$idx + 1}]: row has [string length $row] pixels, expected $w"
        }
        lappend grid $row
    }
    return $grid
}

proc parse_sprite {src} {
    set fh [open $src r]
    set lines [split [read $fh] "\n"]
    close $fh

    set w 0
    set h 0
    set palette [dict create]
    set base {}
    set frames {}

    for {set idx 0} {$idx < [llength $lines]} {incr idx} {
        set line [string trim [lindex $lines $idx]]
        if {$line eq "" || [string index $line 0] eq "#"} { continue }
        set words [regexp -all -inline {\S+} $line]
        switch -- [lindex $words 0] {
            size {
                set w [lindex $words 1]
                set h [lindex $words 2]
                if {![is_pow2 $w] || ![is_pow2 $h]} { fail "$src: size must be powers of two" }
            }
            palette {
                set ch  [lindex $words 1]
                set hex [string toupper [lindex $words 2]]
                if {[string length $ch] != 1 || ![regexp {^[0-9A-F]{2}$} $hex]} {
                    fail "$src line [expr {$idx + 1}]: bad palette entry"
                }
                dict set palette $ch [list $hex [join [lrange $words 3 end] " "]]
            }
            base {
                if {$w == 0} { fail "$src: size must come before base" }
                set base [read_grid $lines idx $w $h $src]
            }
            frame {
                if {$w == 0} { fail "$src: size must come before frame" }
                lappend frames [read_grid $lines idx $w $h $src]
            }
            default { fail "$src line [expr {$idx + 1}]: unknown keyword '[lindex $words 0]'" }
        }
    }

    if {[llength $frames] == 0 && [llength $base] > 0} { set frames [list $base] }
    if {[llength $frames] == 0} { fail "$src: no frames" }
    if {![dict exists $palette "."]} { fail "$src: palette must define '.' (transparent)" }
    if {[lindex [dict get $palette "."] 0] ne "FF"} { fail "$src: '.' must map to FF" }

    # Resolve overlays into full images of hex values.
    set images {}
    foreach frame $frames {
        set image {}
        for {set y 0} {$y < $h} {incr y} {
            for {set x 0} {$x < $w} {incr x} {
                set ch [string index [lindex $frame $y] $x]
                if {[llength $base] > 0} {
                    if {$ch eq "."} { set ch [string index [lindex $base $y] $x] }
                    if {$ch eq "_"} { set ch "." }
                }
                if {![dict exists $palette $ch]} { fail "$src: pixel '$ch' is not in the palette" }
                set hex [lindex [dict get $palette $ch] 0]
                if {$hex eq "FF" && $ch ne "."} { fail "$src: '$ch' uses FF, which is reserved for transparency" }
                lappend image $hex
            }
        }
        lappend images $image
    }
    return [list $w $h $palette $images]
}

proc write_mif {dst src w h images} {
    set nFrames [llength $images]
    set depth [expr {$nFrames * $w * $h}]
    set addrDigits [string length [format %X [expr {$depth - 1}]]]
    set fh [open $dst w]
    fconfigure $fh -translation lf
    puts $fh "-- Generated by tools/sprite_tool.tcl from [file tail $src]; edit the .txt, not this file."
    puts $fh "-- ${w}x${h} pixels, $nFrames frame(s), address = frame * [expr {$w * $h}] + y * $w + x"
    puts $fh "DEPTH = $depth;"
    puts $fh "WIDTH = 8;"
    puts $fh "ADDRESS_RADIX = HEX;"
    puts $fh "DATA_RADIX = HEX;"
    puts $fh "CONTENT BEGIN"
    set addr 0
    foreach image $images {
        foreach hex $image {
            puts $fh [format "%0*X : %s;" $addrDigits $addr $hex]
            incr addr
        }
    }
    puts $fh "END;"
    close $fh
    return $depth
}

proc water_ramp {} {
    set pkg [file join [file dirname [info script]] .. fpga RTL PKG palette_pkg.sv]
    set fh [open $pkg r]
    set text [read $fh]
    close $fh
    set ramp {}
    for {set i 0} {$i <= 8} {incr i} {
        if {![regexp "C_WATER_$i\\s*=\\s*\\{3'd(\\d),\\s*3'd(\\d),\\s*2'd(\\d)\\}" $text -> r g b]} {
            fail "cannot find C_WATER_$i in $pkg"
        }
        lappend ramp [expr {($r << 5) | ($g << 2) | $b}]
    }
    return $ramp
}

proc write_preview {dst src w h palette images} {
    set name [file rootname [file tail $src]]
    set jsFrames {}
    foreach image $images {
        set vals {}
        foreach hex $image { lappend vals [expr {"0x$hex"}] }
        lappend jsFrames "\[[join $vals ,]\]"
    }
    set jsPalette {}
    dict for {ch entry} $palette {
        lappend jsPalette "\{ch:\"$ch\",v:0x[lindex $entry 0],d:\"[string map {\" '} [lindex $entry 1]]\"\}"
    }
    set bytes [expr {[llength $images] * $w * $h * 8}]

    set fh [open $dst w]
    fconfigure $fh -translation lf
    puts $fh [string map [list \
        @NAME@ $name @W@ $w @H@ $h @N@ [llength $images] @BITS@ $bytes \
        @FRAMES@ [join $jsFrames ",\n"] @PALETTE@ [join $jsPalette ",\n"] \
        @RAMP@ [join [water_ramp] ,]] {<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>@NAME@ sprite preview</title>
<style>
  :root { --bg: #f4f6f8; --fg: #1d2530; --muted: #5b6776; --card: #ffffff; --line: #d8dee6; }
  @media (prefers-color-scheme: dark) {
    :root { --bg: #11161c; --fg: #e3e8ee; --muted: #9aa6b4; --card: #1a2129; --line: #2c3642; }
  }
  body { margin: 0; padding: 16px; background: var(--bg); color: var(--fg);
         font: 15px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif; }
  main { max-width: 1100px; margin: 0 auto; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  h2 { font-size: 16px; margin: 24px 0 8px; }
  p.sub { color: var(--muted); margin: 0 0 16px; }
  .row { display: flex; flex-wrap: wrap; gap: 16px; }
  .card { background: var(--card); border: 1px solid var(--line); border-radius: 10px; padding: 12px; }
  canvas { image-rendering: pixelated; display: block; max-width: 100%; height: auto; }
  .cap { font-size: 13px; color: var(--muted); margin-top: 6px; }
  table { border-collapse: collapse; font-size: 14px; }
  td, th { padding: 4px 10px; border-bottom: 1px solid var(--line); text-align: left; }
  .sw { width: 28px; height: 18px; border: 1px solid var(--line); border-radius: 3px; }
  code { font-family: ui-monospace, Consolas, monospace; }
</style>
</head>
<body>
<main>
  <h1>@NAME@ sprite preview</h1>
  <p class="sub">@W@&times;@H@ pixels, @N@ frame(s), @BITS@ ROM bits. Colours use the same
  RRRGGGBB expansion as the supplied <code>VGA_Controller.sv</code>; transparent pixels show the checkerboard.</p>

  <h2>Frames (12&times;)</h2>
  <div class="row" id="frames"></div>

  <h2>In game, true size (640&times;480 screen, animated 0-1-2-1, bobbing like EASY mode)</h2>
  <div class="card"><canvas id="scene" width="640" height="480" style="width:960px"></canvas>
  <div class="cap">Water is drawn with the same dithered ramp as <code>water_background.sv</code>. Displayed at 1.5&times;.</div></div>

  <h2>Palette</h2>
  <div class="card"><table id="palette"><tr><th>Char</th><th>RRRGGGBB</th><th>On screen</th><th></th><th>Use</th></tr></table></div>
</main>
<script>
const W = @W@, H = @H@;
const FRAMES = [
@FRAMES@
];
const PALETTE = [
@PALETTE@
];
const RAMP = [@RAMP@];
const BAYER = [[0,8,2,10],[12,4,14,6],[3,11,1,9],[15,7,13,5]];

function expand(v) {
  const r = (v >> 5) & 7, g = (v >> 2) & 7, b = v & 3;
  return [(r << 5) | (r & 4 ? 31 : 0), (g << 5) | (g & 4 ? 31 : 0), (b << 6) | (b & 2 ? 63 : 0)];
}
function css(v) { const [r, g, b] = expand(v); return `rgb(${r},${g},${b})`; }

for (const [i, f] of FRAMES.entries()) {
  const S = 12, c = document.createElement("canvas");
  c.width = W * S; c.height = H * S;
  const x = c.getContext("2d");
  for (let py = 0; py < H; py++) for (let px = 0; px < W; px++) {
    const v = f[py * W + px];
    x.fillStyle = v === 0xFF ? (((px + py) & 1) ? "#c9ced6" : "#e9ecf0") : css(v);
    x.fillRect(px * S, py * S, S, S);
  }
  const card = document.createElement("div");
  card.className = "card";
  card.appendChild(c);
  const cap = document.createElement("div");
  cap.className = "cap"; cap.textContent = `frame ${i}`;
  card.appendChild(cap);
  document.getElementById("frames").appendChild(card);
}

const tbl = document.getElementById("palette");
for (const p of PALETTE) {
  const tr = document.createElement("tr");
  const [r, g, b] = expand(p.v);
  tr.innerHTML = `<td><code>${p.ch}</code></td><td><code>${p.v.toString(16).toUpperCase().padStart(2, "0")}</code></td>` +
    `<td><code>#${[r, g, b].map(n => n.toString(16).padStart(2, "0")).join("")}</code></td>` +
    `<td><div class="sw" style="background:${p.v === 0xFF ? "transparent" : css(p.v)}"></div></td><td>${p.d}</td>`;
  tbl.appendChild(tr);
}

const scene = document.getElementById("scene"), sx = scene.getContext("2d");
const water = sx.createImageData(640, 480);
for (let y = 0; y < 480; y++) for (let x = 0; x < 640; x++) {
  const band = (y >> 6) & 7, blend = (y >> 2) & 15;
  const v = RAMP[band + (blend > BAYER[y & 3][x & 3] ? 1 : 0)];
  const [r, g, b] = expand(v), o = (y * 640 + x) * 4;
  water.data.set([r, g, b, 255], o);
}
const order = [0, 1, 2, 1];
let frameCount = 0;
function draw() {
  sx.putImageData(water, 0, 0);
  const f = FRAMES[order[Math.floor(frameCount / 8) % 4] % FRAMES.length];
  const y0 = Math.round(224 + 150 * Math.sin(frameCount * 2 * Math.PI / 171));
  const img = sx.getImageData(144, y0, W, H);
  for (let i = 0; i < W * H; i++) if (f[i] !== 0xFF) img.data.set([...expand(f[i]), 255], i * 4);
  sx.putImageData(img, 144, y0);
  frameCount++;
}
setInterval(draw, 1000 / 72.58);
</script>
</body>
</html>}]
    close $fh
}

set args $quartus(args)
if {[llength $args] < 2} {
    fail "usage: quartus_sh -t tools/sprite_tool.tcl <sprite.txt> <out.mif> \[preview.html\]"
}
lassign $args src mif html
foreach out [list $mif $html] {
    if {$out ne ""} { file mkdir [file dirname $out] }
}
lassign [parse_sprite $src] w h palette images
set depth [write_mif $mif $src $w $h $images]
puts "sprite_tool: $src -> $mif ($depth words x 8 bits = [expr {$depth * 8}] bits)"
if {$html ne ""} {
    write_preview $html $src $w $h $palette $images
    puts "sprite_tool: preview -> $html"
}
